[package]
name = "pico-8-wiki-offline"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]
edition = "2018"

[[bin]]
name = "wiki-dump-to-html"

[dependencies]
parse_mediawiki_dump = "0.1"
parse_wiki_text = "0.1"
